#
#/turtlesim2/sim:
#   ros__parameters:
#      background_b: 255
#      background_g: 86
#      background_r: 150

#/turtlesim3/sim:
#   ros__parameters:
#      background_b: 255
#      background_g: 86
#      background_r: 150

/**:
   ros__parameters:
      background_b: 255
      background_g: 86
      background_r: 150